#!/usr/bin/env bash
# kind environment profile: provisions a self-contained no-GPU cluster.
#
# TLS wiring (verified against kube-prometheus-stack chart v82 CRD):
#   prometheus.prometheusSpec.web is passed as a raw YAML object via --set.
#   The Prometheus Operator WebTLSConfig requires:
#     web.tlsConfig.cert.secret.{name,key}   -- PEM certificate (tls.crt)
#     web.tlsConfig.keySecret.{name,key}     -- PEM private key (tls.key)
#   The chart does NOT auto-create the secret, so we create a self-signed
#   secret named "prometheus-web-tls" BEFORE helm install.
#   The guide's create-tls-secret step reads tls.crt from this same secret.
#
# Idempotency contract:
#   - kind create cluster: guarded by `kind get clusters | grep -qx`
#   - namespaces: kubectl create ... --dry-run=client | kubectl apply -f -
#   - self-signed TLS secret: kubectl create secret ... --dry-run=client | kubectl apply -f -
#   - helm installs: helm upgrade --install
#   - docker pull + kind load: safe to re-run (kind load is idempotent)

CLUSTER="${KIND_CLUSTER:-llmd-autoscaling}"
MON_NS="${MONITORING_NAMESPACE:-llm-d-monitoring}"
GUIDE_NS="${NAMESPACE:-llm-d-optimized-baseline}"
SIM_IMAGE="ghcr.io/llm-d/llm-d-inference-sim:v0.9.0"
_PROFILE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

run_env_provision() {
  local modelserver="$1"

  # 1. Create kind cluster if absent.
  if ! kind get clusters 2>/dev/null | grep -qx "$CLUSTER"; then
    kind create cluster --name "$CLUSTER" \
      --config "${_PROFILE_DIR}/kind-config.yaml"
  fi

  # 2. Create namespaces (idempotent).
  kubectl create namespace "$MON_NS"   --dry-run=client -o yaml | kubectl apply -f -
  kubectl create namespace "$GUIDE_NS" --dry-run=client -o yaml | kubectl apply -f -

  # 3. Create a self-signed TLS secret for the Prometheus web endpoint BEFORE
  #    helm install so the Prometheus pod can start.  The guide's
  #    create-tls-secret step later reads tls.crt from this same secret.
  #
  #    TLS path verified from crd-prometheuses.yaml in kube-prometheus-stack v82:
  #      prometheusSpec.web.tlsConfig.cert.secret.{name,key}
  #      prometheusSpec.web.tlsConfig.keySecret.{name,key}
  #    The secret is NOT auto-generated by the chart.
  if ! kubectl -n "$MON_NS" get secret prometheus-web-tls >/dev/null 2>&1; then
    # Generate a self-signed cert valid for 10 years.
    local _tmpdir
    _tmpdir="$(mktemp -d)"
    openssl req -x509 -newkey rsa:2048 -nodes \
      -keyout "${_tmpdir}/tls.key" \
      -out    "${_tmpdir}/tls.crt" \
      -days   3650 \
      -subj   "/CN=prometheus.${MON_NS}.svc" \
      -addext "subjectAltName=DNS:prometheus-operated.${MON_NS}.svc,DNS:localhost" \
      2>/dev/null
    kubectl -n "$MON_NS" create secret tls prometheus-web-tls \
      --cert="${_tmpdir}/tls.crt" \
      --key="${_tmpdir}/tls.key" \
      --dry-run=client -o yaml | kubectl apply -f -
    rm -rf "${_tmpdir}"
  fi

  # 4. Add helm repos (idempotent; errors mean repo already exists).
  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts >/dev/null 2>&1 || true
  helm repo add kedacore             https://kedacore.github.io/charts             >/dev/null 2>&1 || true
  helm repo update >/dev/null

  # 5. Install kube-prometheus-stack with TLS on the Prometheus web endpoint.
  #    Values path from crd-prometheuses.yaml (chart v82, prometheus-operator API):
  #      prometheus.prometheusSpec.web.tlsConfig.cert.secret.{name,key}
  #      prometheus.prometheusSpec.web.tlsConfig.keySecret.{name,key}
  #    Secret "prometheus-web-tls" created above (keys: tls.crt / tls.key).
  helm upgrade --install kube-prometheus-stack \
    prometheus-community/kube-prometheus-stack \
    --namespace "$MON_NS" \
    --set "prometheus.prometheusSpec.web.tlsConfig.cert.secret.name=prometheus-web-tls" \
    --set "prometheus.prometheusSpec.web.tlsConfig.cert.secret.key=tls.crt" \
    --set "prometheus.prometheusSpec.web.tlsConfig.keySecret.name=prometheus-web-tls" \
    --set "prometheus.prometheusSpec.web.tlsConfig.keySecret.key=tls.key" \
    --wait --timeout 10m

  # 6. Install KEDA and prometheus-adapter.
  helm upgrade --install keda \
    kedacore/keda \
    --namespace "$MON_NS" \
    --wait --timeout 5m

  helm upgrade --install prometheus-adapter \
    prometheus-community/prometheus-adapter \
    --namespace "$MON_NS" \
    --wait --timeout 5m

  # 7. Pre-load the sim image so pods start without a registry pull.
  docker pull "$SIM_IMAGE"
  kind load docker-image "$SIM_IMAGE" --name "$CLUSTER"

  run_env_verify_monitoring
}

run_env_verify_monitoring() {
  kubectl -n "$MON_NS" get deploy >/dev/null
  echo "  monitoring namespace $MON_NS reachable"
}
