apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: modelserver
          command: ["/app/llm-d-inference-sim"]
          args:
            - "--model=Qwen/Qwen3-32B"
            - "--served-model-name=Qwen/Qwen3-32B"
            - "--port=8000"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: modelserver
          livenessProbe:
            httpGet:
              path: /health/ready
              port: modelserver
          startupProbe:
            httpGet:
              path: /v1/models
              port: modelserver
          resources:
            requests:
              cpu: "100m"
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
